- .circleci/config.yml
- .coveragerc
This PR adds the required configuration for using CircleCI for this module, as well as for running unit tests and submitting the test coverage to Codecov.
> Add support for CI integration, testing and coverage analysis

- setup.py
Fix classifier.
Update project's main homepage, author, author email, description and keywords.
Add long_description_content_type.
> Prepare setup.py to upload the release to pypi.

- ospd/parser.py
Fix --help and add additional defaults in --help
> Parser defaults

- ospd/ospd.py
- tests/test_scan_and_result.py
Decode() output before sending.
> Fix get_performance

- CHANGELOG.md
- ospd/__init__.py
> Version bump

- CHANGELOG.md
- README.md
- ospd/__init__.py
- setup.py
Set stable release
Update Badges
Update README.md and CHANGELOG.md
> Prepare release v2.0.0

- CHANGELOG.md
- Pipfile.lock
- setup.py
> Fix classifier in setup.py

- CHANGELOG.md
- ospd/server.py
It was trying to set the permissions on the unix socket before creating it.
> Fix set permission on unix socket.

- doc/OSP.xml
> [2.0] A couple of OSP documentation fixes and improvements

- .circleci/config.yml
Run black --check on the ospd code base.
> Add check for code formatting to circleci

- CHANGELOG.md
- ospd/misc.py
- ospd/network.py
For compatibility purposes, a finished host can be add to the excluded hosts
by the client.
> Remove from exclude_host list the hosts passed as finished too.

- ospd/command/command.py
- ospd/command/registry.py
- ospd/ospd.py
- tests/command/__init__.py
- tests/command/test_command.py
- tests/command/test_commands.py
- tests/command/test_registry.py
Especially add some more tests.
> Improve Command Registry

- ospd/command/command.py
- ospd/protocol.py
- tests/command/test_commands.py
Don't parse parallel attribute at all. Just check if it is set and raise
a warning.
> Update start scan parallel

- ospd/timer.py
with Timer('foo'):
bar()
Will add a debug log about how long the exectution of bar did take.
> Add a Timer class for easy profiling of durations

- ospd/xml.py
- tests/test_xml.py
> Escape control chars, not supported in xml

- ospd/ospd.py
> [2.0] Add oid to ERRMSG type results

- ospd/command/command.py
Do not allow to start a scan during initialization.
> Fix start_scan command.

- CHANGELOG.md
- ospd/__init__.py
Version bump
Update changelog with missing entries.
> Prepare for release 2.0.1

- CHANGELOG.md
- ospd/server.py
This fix tls conexion problems with some clients not supporting tls v1.3
> Use PROTOCOL_TLSv1_2 instead of PROTOCOL_TLS

- ospd/scan.py
> Fix a typo.

- ospd/ospd.py
Backport of #308 to the ospd-2.0 branch.
Not sure if older branches like ospd-1.3 are also still active?
> [2.0] Mention PID in the scan stopping / stopped log messages.

- ospd/command/command.py
- ospd/command/registry.py
- ospd/cvss.py
- ospd/datapickler.py
- ospd/errors.py
- ospd/main.py
- ospd/misc.py
- ospd/network.py
- ospd/ospd.py
- ospd/ospd_ssh.py
- ospd/protocol.py
- ospd/resultlist.py
- ospd/scan.py
- ospd/server.py
- ospd/vtfilter.py
- ospd/vts.py
- ospd/xml.py
- poetry.lock
- pyproject.toml
**What**:
Bump black version from 19.10b0 to 20.8b1
**Why**:
Test fails in Depandabot's PR. New black report format issues.
**Checklist**:
> Bump black version

- ospd/command/command.py
- ospd/command/registry.py
- ospd/cvss.py
- ospd/datapickler.py
- ospd/errors.py
- ospd/main.py
- ospd/misc.py
- ospd/network.py
- ospd/ospd.py
- ospd/ospd_ssh.py
- ospd/parser.py
- ospd/protocol.py
- ospd/resultlist.py
- ospd/scan.py
- ospd/server.py
- ospd/vtfilter.py
- ospd/vts.py
- ospd/xml.py
- poetry.lock
- pyproject.toml
**What**:
Bump black and pylint versions
**Checklist**:
> Bump black and pylint versions

- CHANGELOG.md
- ospd/ospd.py
- ospd/scan.py
- poetry.lock
- tests/test_scan_and_result.py
**What**:
**Why**:
**How**:
**Checklist**:
> Merge ospd-20.08 in master

- CHANGELOG.md
- ospd/ospd.py
- ospd/scan.py
- tests/test_scan_and_result.py
**What**:
**Why**:
**How**:
**Checklist**:
>  Merge branch 'ospd-20.08' into master

- doc/OSP.xml
**What**:
**Why**:
**How**:
**Checklist**:
> ￼ Merge branch 'ospd-20.08' into ospd-21.04

- .mergify.yml
**What**:
Add mergify config file
**Why**:
**How**:
**Checklist**:
> Add mergify config file

- poetry.lock
- pyproject.toml
**What**:
Updating pylint (2.7.2 -> 2.7.4) and poetry.lock to solve conflicts
**Why**:
Dependabot couln't because a conflict.
**How**:
**Checklist**:
> Update pylint dependency and solve conflict

- CHANGELOG.md
- poetry.lock
**What**:
Prepare for release 21.04.0
**Why**:
**How**:
**Checklist**:
> Prepare for release 21.04.0

- CHANGELOG.md
- ospd/network.py
**What**:
Remove log message which was used during dev/debug
**Why**:
Because I forgot to remove it in my last PR.
**How**:
**Checklist**:
> Remove log message which was used during dev/debug

- CHANGELOG.md
- ospd/command/command.py
- ospd/ospd.py
**What**:
Remove dry run from ospd
**Why**:
Although it is still supported as scanner param. If required, should be added as method in wrapper.
**How**:
Start a scan with the scanner parameter <dry_run>1</dry_run>
**Checklist**:
> Remove dry run from ospd

- .github/workflows/release-pontos-patch.yml
**What**:
**Why**:
**How**:
**Checklist**:
> [release] [21.4.1] Fix workflow

- poetry.lock
- pyproject.toml
**What**:
**Why**:
**How**:
**Checklist**:
> [release] [20.8.3] Release ospd

- .github/workflows/ci-python.yml
- .github/workflows/codeql-analysis-python.yml
**What**:
**Why**:
**How**:
**Checklist**:
> Add branch middleware

- .github/workflows/ci-python.yml
- .github/workflows/codeql-analysis-python.yml
- CHANGELOG.md
- ospd/parser.py
**What**:
Reintroduce https://github.com/greenbone/ospd/pull/400  after rebase into new branch middleware.
**Why**:
Separation of feature branch and master.
**How**:
**Checklist**:
> Move MQTT feature into new branch

- CHANGELOG.md
- ospd/ospd.py
**What**:
Backport of https://github.com/greenbone/ospd/pull/432
**Why**:
**How**:
**Checklist**:
> Improve structure 21.04

- ospd/ospd.py
- tests/helper.py
**What**:
Fix some pylint issues.
Different parameter name in overridden method.
Use items() in for loop.
**Why**:
Pass CI.
**How**:
**Checklist**:
> Fix pylint on master
