greenbone/ospd

INSTALL
doc/INSTALL-ospd-scanner
setup.py

Primarily this changes the supported Python version to Python 3 as minimum.
Next, the documentation is updated accordingly and the guide about installing
a ospd-based scanner implementation is separated into its own file for later
reference from ospd-scanner packages. This makes it easier to maintain
the documentation which is shared by all of the ospd-based implementations.

Update documentation and dependencies

---

INSTALL
README.md
doc/INSTALL-ospd-scanner
doc/OSP.xml
ospd/misc.py
ospd/ospd.py
setup.py

This commit fixes a number of spelling mistakes, mainly in documentation
and log messages.

Address multiple typos

---

tests/test_target_convert.py

In case getfqdn("127.0.0.1") does not return localhost.

Mock socket.getfqdn to return "localhost".

---

ospd/config.py
ospd/main.py
ospd/parser.py
tests/test_argument_parser.py

All option have a default value. This option are overwritten if this
option is passed as command line argument.
If there is config file, is loaded and the option
listed in it will be set as the valid one, but they will be still
overwritten by the ones passed as cmd option.
This means that cmd options have priority over the other ones.
The config file must have a section with the wrapper name. As ospd
is a base lib for multiple wrappers, each wrapper can have each own
section with its configuration.
The default path for the config file is /home/<user>/.config/ospd.conf
E.g. for ospd-openvas:
`[OSPD - openvas]`
`unix_socket = /tmp/openvas.sock`
`log_level = DEBUG`

Add support for configuration file.

---

ospd/main.py
ospd/parser.py
ospd/server.py

It must be passed in octal format
E.g. for the config file:
`socket_mode = 0o770`

Add option to set unix socket mode permission.

---

ospd/main.py
ospd/misc.py
ospd/parser.py

Adds the --pid-file option in the parser.
Add method to create and remove the pid file.
Set the signal handler and atexit to remove the pid file when the daemon finishes.
How to:
by default, the pid path is /run/ospd/ospd.py. You will have to create the directory and set the right permissions.
```
sudo mkdir /run/ospd`
sudo chown jnicola:jnicola /run/ospd
```
Or you can run ospd-daemon with the option --pid-file and use an existing directory with rw permissions:
```
ospd-openvas --pid-file /tmp/ospd-openvas.pid
```
This is also valid to do it with the config file, adding under the right section the option. E.g.:
```
[OSPD - openvas]
log_level = DEBUG
socket_mode = 0o770
unix_socket = /tmp/openvas.sock
pid_file = /tmp/openvas.sock
```

Create pid file to avoid having two daemons.

---

ospd/misc.py

This avoid the pid file to be removed when a child process exits.

Only the main process can remove the pid file.

---

ospd/ospd.py
tests/test_scan_and_result.py

Do not call stop_scan if the task was already set as stopped and remove senseless log results.

Improve handling of stopped tasks

---

ospd/main.py

Force foreground to True if the --version option has been passed.
This avoid to print in the syslog (in case it is the default log facility),
since in this case the stdout is redirected.

Fix --version option

---

doc/OSP.xml
ospd/ospd.py
tests/test_scan_and_result.py

Allows to execute a external program/script and get the response.
The program must be named 'gvmcg' and should receive up to 3 arguments
called start, end and titles.
Example with gvm-cli:
```
gvm-cli --protocol OSP socket --socketpath=/run/ospd/openvas.sock --xml "<get_performance start='0' titles='titles'/>"
```

Add <get_performance>

---

ospd/main.py
ospd/parser.py

There was a default unix socket, therefore it will always start a
server which listens in a unix socket.
If a valid port is set, it will listen in a tls socket

Fix tls options. Avoid to listen always in a unix socket.

---

ospd/ospd.py

Some scans can finish cleanly even if the don't scan all the hosts in the target string.
This produced to have an ended scan with a incomplete progress scan percentage (< 100%), which was treated as an error. Now this function allow to do a check and to decide if it is an error or the scan finished cleanly.

Add method to check if a target finished cleanly or crashed.

---

ospd/misc.py
ospd/ospd.py
tests/test_scan_and_result.py

This will be set when it calculates the progress from the different
host and target.
Now the multi target tasks work again.
Also rename methods

Fix multi target tasks

---

CHANGELOG.md
ospd/main.py
ospd/ospd.py
ospd/parser.py
ospd/server.py

OSPD can now answer to multiple clients in parallel without a waiting time.
Before, if a client did a request, it should wait until the response to a
first request had been completely sent.
Basically, it replace the bind and select methods from socket module with
a start method which uses instead socketserver and threading modules.

Add support to handle multiple requests simultaneously.

---

CHANGELOG.md
ospd/ospd.py

For each target a host detail result with the "host_status" was generated, but also an extra host in the report if the host scanned differs from the target.
E.g 1 : target = 127.0.0.1, then scanned host = 127.0.0.1 ----> no extra host in the report.
E.g 2 target = localhost, then scanned host = 127.0.0.1 ----> an extra host in the report with out info. 
The target status will be logged, and no result will be sent to the client.
In future, if a result is necessary, it must be added from the wrapper and not from the base module.

Do not add a host detail result with the host status.

---

CHANGELOG.md
ospd/ospd.py

(2.0) Do not add a host detail result with the host status.

---

CHANGELOG.md
ospd/server.py

It was trying to set the permissions on the unix socket before creating it.

[ospd-2.0] Fix set permission on unix socket.

---

CHANGELOG.md
ospd/ospd.py

In case of the port list, it could flood the log file.
For the amount of result, it can be a bit confused, since many results
are "host details" which are not shown in gsa.

Set loglevel to debug for some message.

---

CHANGELOG.md
ospd/ospd.py

In case of the port list, it could flood the log file.
For the amount of result, it can be a bit confused, since many results
are "host details" which are not shown in gsa.

[2.0.0] Set loglevel to debug for some message.

---

CHANGELOG.md
ospd/ospd.py

If no vts matches the filter, returns an empty element.

[2.0] Fix VT Filter.

---

CHANGELOG.md
ospd/ospd.py

If no vts matches the filter, returns an empty element.

Fix VT Filter.

---

CHANGELOG.md
ospd/ospd.py

It checked only for STOPPED before resuming a scan.
It checks now also for FINISHED and RUNNING status and avoid
to restart a scan which is already running or finished.

Check the existence and status of an scan_id

---

CHANGELOG.md
ospd/misc.py
ospd/network.py

For compatibility purposes, a finished host can be add to the excluded hosts
by the client.

[2.0] Remove from exclude_host list the hosts passed as finished too.

---

CHANGELOG.md
ospd/ospd.py

This release the children faster, in case no client is collecting results.
Make the join() non-blocking.

Add wait_for_children().

---

ospd/main.py

Handle own errors safely and only display error messages instead of full
tracebacks in the console.

Don't print tracebacks from OspdErrors

---

CHANGELOG.md
ospd/ospd.py

A new process is spawn, and it will load the vts in a dictionary.
This process run and keep the collection.
The main process it is lighter now. Therefore, the new fork()'ed scan
processes inherit less memory.

Create data manager and spawn new process to keep the vts dictionary.

---

CHANGELOG.md
ospd/main.py

Run daemon.check before daemon.init now. Daemon.check should fail early
before cost intensive init is run.

Update daemon run sequence

---

CHANGELOG.md
ospd/command/__init__.py
ospd/command/command.py
ospd/ospd.py
ospd/vtfilter.py
ospd/xml.py
tests/command/test_commands.py
tests/helper.py
tests/test_scan_and_result.py

Before the response was a single huge xml element in a string, made before sending
which caused a huge memory consumption. Now the amount of memory used for this cmd
is quite smaller.

Improve get_vts cmd response, sending the vts piece by piece.

---

CHANGELOG.md
ospd/command/command.py
ospd/ospd.py

Wait for the scan process to be stopped before delete it from the process table.

Fix stop scan.

---

CHANGELOG.md
ospd/protocol.py

Running the test with python3 -m setup.py tests, a test was failing
while running with python3 -m unittest, it doesn't.
The scanner_params variable was overwritten with the xml Element and
passed dictionary was lost.
A second issue was the et.Element type. isinstance() in xml.simple_response_str()
does not recognize et.Element as Element, and therefore the parameter was not added to the final
response. For this reason, Element is used in protocol instead of et.Element.

Fix get_scanner_details().

---

CHANGELOG.md
ospd/main.py
ospd/misc.py
ospd/ospd.py

This allows to create the socket and give a response to the client, while
the server is still in the initialization process.

Start the server before initialize.

---

CHANGELOG.md
Pipfile
Pipfile.lock
doc/OSP.xml
ospd/command/command.py
setup.py
tests/command/test_commands.py
tests/command/test_registry.py

Add a get_memory_usage command. Currently it is only possible to list the memory usage of the main process and its direct children.

Get memory usage

---

ospd/command/command.py
ospd/ospd.py
ospd/ospd_ssh.py
ospd/protocol.py
ospd/scan.py
tests/helper.py
tests/test_scan_and_result.py
tests/test_ssh_daemon.py

Adjust methods and scan_info structure to pass/get a single target.
Remove the parallel process checks
Launch the single scan from start scan instead of using parallel scan.
Parallel attribute for <start_scan> cmd is ignored.

Remove multitarget

---

ospd/scan.py

This allows to release memory in case the vts are not used anymore
during the scan.

Add methods to remove the vts list from the scan table.

---

ospd/ospd.py

SCHEDULER_CHECK_PERIODS was defined but never used. Adjust it to 10
seconds and use it now.

Use defined constant for the scheduler interval

---

CHANGELOG.md
ospd/ospd.py
ospd/xml.py
tests/test_scan_and_result.py

Since the VTs are not in the ospd cache anymore, they are get from a a generator to be sent to the client.
The generator must be implemented in the wrapper and should return a single vt dictionary to be converted in xml format and to be sent to the client.
Therefore, get_vt_xml() does not receive a vt id anymore, but the vt dictionary.

Send the VTs by chunk as response for get_vts

---

CHANGELOG.md
ospd/parser.py
tests/test_argument_parser.py

By default  the directory is /var/run/ospd. In this directory can be placed lock files in case of need.
E.g.: during feed update to block other processes.

Add lock-file-dir configuration option.

---

ospd/command/command.py
ospd/ospd.py

It is not implemented by default, therefore the whole collection
will be return if this method is not implemented in the wrapper side.

Extend get_vt_iterator() with a vt selection parameter.

---

ospd/xml.py

since the default encoding format for xml.etree.Element.tostring() is us-ascii.
￼Escape attributes values as well.

Encode the xml string in utf-8 before sending it

---

tests/test_scan_and_result.py

Avoid a race condition, when the status is not changed but it has already an end_time
Remove the assert, since this is not supposed to be tested by this test.

Improve test

---

ospd/xml.py

Also, cast value to str, before passing to quoteattr()
Also, use escape_ctrl_chars where necessary

Escape attribute value

---

ospd/vts.py

If the original vts collection is sorted for the calculation, the vts collection is copied into the main process. So, a deep copy is made to be sorted and released at the end. This generates a memory usage peak during time interval.

Copy the vts for calculation

---

ospd/vts.py
tests/test_vts.py

Preserve the order in which the vts were added to the dictionary. This avoid the copy of the dictionary to be sorted.
Also update the test, and add a new one to test the include_vt_params= False

Don't sort the vts for hash calculation.

---

ospd/ospd.py
ospd/resultlist.py
ospd/scan.py
tests/test_scan_and_result.py
tests/test_vts.py

This allows to access the scan table less time. As the scan table is in a separated process, accessing the shared memory makes the writing of result for large scan quite slow.
Now this is improved.

Add support for updating results, finished hosts and host progresses in batch.

---

ospd/command/command.py
ospd/ospd.py
ospd/parser.py
tests/command/test_commands.py

Add max_scans cmd option and check if was already reached before starting a new scan.
Add check_free_memory cmd option and check if there is enough free memory before starting a scan.
The options are independent of each other and can be combined .
The memory check is experimental and must be improved.
At the moment the start scan will be rejected.

Check for max scans before starting a new scan

---

.circleci/config.yml

Run builds tests on Python 3.8 too.

Add Python 3.8 to CircleCI config

---

ospd/command/command.py
ospd/ospd.py

These changes make ospd independent of a VT cache. Important for those scanner wrappers which does not need a cache or even not have plugin set.

Receive storage type argument at init.

---

CHANGELOG.md
ospd/ospd.py
tests/test_scan_and_result.py

Instead return an error. This is to avoid a client receive a malformed
vt collection during a vt upload.
Black modified some methods automatically.

Add initialized flag. If active, don't response to get_vts.

---

ospd/command/command.py
ospd/ospd.py
ospd/vts.py
tests/test_scan_and_result.py

This allows to block the use of the cache by one process and avoid
other process to do an action on the cache.
Eg. update vts cache during response of get_vts cmd.

Add flag to advice that the cache is being used for a process.

---

CHANGELOG.md
doc/OSP.xml
ospd/command/command.py
ospd/ospd.py
ospd/scan.py
ospd/xml.py
tests/test_scan_and_result.py

Dead host can be set directly as dead, or can be recognized as dead if the scan progress is -1
The list of finished hosts is not kept anymore, and therefore support for resume task is removed.
Only the amount of finished  hosts (alive or dead) are stored and the scan progress calculation has been changed. The dead host are not taken in account for calculation.
A new attribute "progress" is added for <get_scans> to get more information about the scan progress. Per default is disabled. 
Usage example:
```<get_scans details='0' progress='1'/>```

Improve handling of dead hosts and improve scan progress calculation

---

ospd/server.py

Use daemon mode to circrumvent a memory leak (reported at https://bugs.python.org/issue37193).
Daemonic threads are killed immediately on shutdown by the python interpreter without waiting for until they are finished.
Maybe block_on_close = True could work too. In that case the interpreter waits for the threads to finish but doesn't track them in the _threads list.
It seems that the interpreter always waits for non-daemonic threads before finishing. Therefore I currently wonder why the Python devs added thread joining to the ThreadingMixIn (https://github.com/python/cpython/blob/3.7/Lib/socketserver.py#L674) at all when it is done on shutdown automatically already.
Short example script (works with Python 2.7 too) for playing with the different threading behavior.
```python
from __future__ …
```

Use daemon mode for python 3.7

---

CHANGELOG.md
ospd/main.py

This avoid to leave the pid file because interruptions during the
cleanup, especially when the --foreground mode is enabled and the user
tries to kill ospd-openvas many times with ctrl+c

Ignore subsequent SIGINT once inside exit_cleanup()

---

ospd/command/command.py
ospd/ospd.py
ospd/scan.py
tests/command/test_commands.py
tests/helper.py
tests/test_scan_and_result.py
tests/test_ssh_daemon.py

When a new scan is started, it will not be started directly, but the data information will be stored in the scan table in data manager. The scan is set as PENDING (new scan status added with this PR). 
A new method call from inside the main loop will check for a PENDING scan and will launch the scan in a new fork()'ed process.
This avoid to fork the new scan process with all the data objects inherited from the parent process.
This reduces the memory usage of the new process (data manager and task processes) from ~110MB to ~30MB, for a full and fast single host target scan.

Create a pre fork()'ed data manager to store scan data information

---

CHANGELOG.md
ospd/ospd.py
tests/helper.py
tests/test_scan_and_result.py

When check for enough free memory before starting a scan, check for available memory now
When the command line 'free -h' is called, the output shows two different values: available and free memory. Available is the one with more fluctuation and the one we should check instead of free, because it gives a more realistic value for checking if there is enough memory before starting a queued scan. 
More info can be found in the free command man page.

Use available memory instead of free memory

---

ospd/command/command.py
ospd/ospd.py
tests/test_scan_and_result.py
tests/test_ssh_daemon.py

The scan is queued and will be started when the feed update finishes.

Allow a client to request start_scan during feed update

---

CHANGELOG.md
ospd/command/command.py
tests/test_scan_and_result.py

If the attribute version_only is set, does not send any vt in the response.

Extend get_vts with attribute version_only and return the version

---

CHANGELOG.md
doc/OSP.xml
ospd/command/command.py

* With attribute `list_all` set to `1` all available scanner parameters are listed. 
* Per default `list_all` is considered as `0` and only the parameters visible to the client are shown.
* This way we do not have to change clients (e.g. gsa) for only showing specific parameters to the user.
Depends on:
https://github.com/greenbone/ospd-openvas/pull/293

Add attribute to <get_scanner_details> for showing all available parameters

---

CHANGELOG.md
ospd/scan.py
tests/test_scan_and_result.py

The scans table is accessed by different processes and the iterated dictionary can
change it size.
The given case was that a new task is being queued (add info in the scans table) at same time a task is being taken from the queue to be started (both process access the scan table). But this will solve issues like a finished scan being removed from the scans table during a scans_table iteration.

Don't iterate directly over the scans table, as it can change during the iteration.

---

CHANGELOG.md
ospd/command/command.py
ospd/ospd.py
ospd/scan.py

Do not add all params which are in the OSPD_PARAMS dict to the params which are set as scan preferences.
Depends on: 
https://github.com/greenbone/ospd-openvas/pull/297

Do not send all params as scanner prefs

---

ospd/ospd.py

Noticed the following entry while checking some logs:
> OSPD[235] 2020-08-01 17:02:03,615: INFO: (ospd.ospd) a15f45b4-034e-48af-9f68-be58e9e83f09: Scan stopping 1675.
Without checking the code it is completely unclear what the last "1675" means. Adding the "PID" text gives some more context.
I'm not absolutely sure if `scan_process.ident` is indeed the PID but a few lines below the following comparison is done so this might be right:
```
if scan_process.ident != os.getpid():
```

[20.08] Mention PID in the scan stopping / stopped log messages.

---

CHANGELOG.md
pyproject.toml

Using a multiline description breaks the METADATA file in the wheel
distributable. pip wasn't able to install the dependencies of ospd.

Fix description for poetry in pyproject.toml

---

ospd/command/command.py
ospd/datapickler.py
ospd/ospd.py
ospd/parser.py
ospd/server.py
poetry.lock

**What**:
Handle newly introduced raise-missing-from feature by either raise from
the catched exception explicitly or by surpressing the original
traceback.
```
except Error as e:
raise MyException()
```
is actually a
```
except Error as e:
raise MyException() from e
```
See https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement
for all details.
**Why**:
A new version of pylint has been released.
**How**:
`poetry run pylint --disable=R ospd tests`
**Checklist**:

Update to pylint 2.6.0

---

CHANGELOG.md
ospd/ospd.py

**What**:
Use the same version for the protocol as for the module.
**How**:
Install and check with ospd-openvas --version
or with gvm-cli, with the <get_version/> command.
**Checklist**:

Fix OSP version

---

CHANGELOG.md
doc/OSP.xml
ospd/protocol.py

**What**:
Add target option for setting dedicated port list for alive detection .
Depends on:
https://github.com/greenbone/ospd-openvas/pull/327
https://github.com/greenbone/gvm-libs/pull/391
**Why**:
It enhances the flexibility when doing alive scans.
**How**:
Used gvm-cli for scans. Added <alive_test_ports>22,80<alive_test_ports> and checked with a print if these ports were actually used during a scan. Checked if defaults were used if no alive_test_ports was provided.
**Checklist**:

Add target option for setting dedicated port list for alive detection 

---

CHANGELOG.md
ospd/ospd.py
ospd/scan.py
tests/test_scan_and_result.py

**What**:
Allow the scanner to update total count of hosts.
**Why**:
In some cases it can differ to the one calculated from original target string
E.g. OpenVAS will remove duplicated hosts, unresolved hostname and
add new hosts in cases a hostname resolves to more than one IP address
**How**:
Run a scan against a hostname target which resolves to more than one ip address.
**Checklist**:

Allow the scanner to update total count of hosts.

---

CHANGELOG.md
doc/OSP.xml
ospd/protocol.py
tests/test_scan_and_result.py

**What**:
Instead of using a bit field which entails all alive tests we can now also use xml elements for every alive test method.
Depends on:
https://github.com/greenbone/ospd-openvas/pull/331
**Why**:
Better usability.
**How**:
Tested with python-gvm and following target description with different configurations.
```
<target>
<alive_test_methods>
<icmp>0</icmp>
<tcp_ack>0</tcp_ack>
<tcp_syn>0</tcp_syn>
<arp>0</arp>
<consider_alive>0</consider_alive>
</alive_test_methods>
<hosts>127.0.0.1</hosts>
</target>
```
**Checklist**:

Add new interface for adding alive test methods

---

CHANGELOG.md
ospd/protocol.py
tests/test_scan_and_result.py

**What**:
Set empty string as value when there is an credential param without  value
**Why**:
The string "None" was sent as preference value instead of the empty string.
**How**:
Run a scan with an snmp credential without community. With this patch, you should not see a result indicating failure for snmp v1|2c. Before, a result was shown, as the script checked the snmp with community "None"
**Checklist**:

Use empty string instead of None for credentials value

---

CHANGELOG.md
ospd/network.py
tests/test_target_convert.py

**What**:
For subnet with mask lower than /24, ip addresses ending in .0 are allowed.
This fix add support for ranges including the address ended with .0.
**Why**:
Because it possible that a host has an IP address ended with .0
**How**:
Start a scan against the target "10.128.64.0-2"
**Checklist**:

Fix convertion from ipv4 range to list of addresses.

---

ospd/misc.py

The normal behavior of the pidfile is to prevent the daemon to be run twice.
When the ospd-openvas daemon dies unexpectedly or it is killed with SIGKILL (-9) signal,
leaves the pid file, which prevent the daemon to start again.
If this is the case, the pidfile must be removed manually.
**What**:
Add more information and problem resolution.
**Why**:
The normal behavior of the pidfile is to prevent the daemon to be run twice.
When the ospd-openvas daemon dies unexpectedly or it is killed with SIGKILL (-9) signal,
leaves the pid file, which prevent the daemon to start again.
If this is the case, the pidfile must be removed manually.
**How**:
Kill -9 ospd-openvas and restart. The new message with the hint to solve the problem should be shown in the log file
**Checklist**:

Add more information and problem resolution.

---

CHANGELOG.md
ospd/network.py
tests/test_target_convert.py

**What**:
Return an empty list in case of malformed host in the target list.
This avoid OSPD to crash during calculation of the scan progress.
Now in conjunction with greenbone/openvas#625 the scan finishes with errors, but nicely.
**Why**:
OSPD check the length of the host list during the scan progress calculation. As the target is not empty, but with errors, the scan started but on error it had returned None, which caused ospd to crash.
**How**:
Start a scan with gvm-cli (gsa already checks for malformed target) wiht 192.168.0.1/32 as host target.
**Checklist**:

Return an empty list in case of malformed host in the target list.

---

CHANGELOG.md
ospd/ospd.py
ospd/scan.py

**What**:
Add debug level log messages
**Why**:
For debugging purposes.
**How**:
Set log level to debug and run a scan.
**Checklist**:

Add debug level log messages

---

CHANGELOG.md
ospd/ospd.py
ospd/scan.py
tests/test_scan_and_result.py

**What**:
Always set end_time for interrupted scans.
**Why**:
end-time was set via set_scan_status (stopped). Now, the scan can be interrupted directly and the end time will be set.
**How**:
Interrupt a running scan and check with <get_scans="SCAN-ID"/>that the end_time is set.
**Checklist**:

Always set end_time for interrupted scans.

---

CHANGELOG.md
ospd/scan.py

**What**:
Initialize end_time with create_scan
**Why**:
Some methods assume `end_time` is set.
Close issue greenbone/ospd-openvas#361
**How**:
Set the option `scaninfo_store_time` and start a scan. Without this patch, the scan crashed. 
**Checklist**:

Initialize end_time with create_scan

---

CHANGELOG.md
ospd/scan.py
tests/test_scan_and_result.py

**What**:
The value set by the server has priority over the value
calculated from the original target list by ospd.
As ospd is not intelligent enough to check the amount of valid
hosts, check for duplicated or invalid hosts, consider a negative
value set for the server, in case it detects an invalid target string
or a different amount than the orignal amount in the target list.
**Why**:
Let ospd to set a scan with an invalid target as `finished` instead of interrupted, but there is no other result than the error message to inform the client about the invalid target.
**How**:
- Set debug log level in ospd.
- Start a scan with an invalid target list (only possible via gvm-cli, as gsa wont you to create a invalid target).
- check with `<get_scans>` that the scan results xml element has …

Fix get_count_total(). Accept -1 value set by the server.

---

ospd/ospd.py
ospd/scan.py

From codespell:
```
./ospd/ospd.py:1298: succesfully ==> successfully
./ospd/scan.py:402: orignal ==> original
```

Fix typos.

---

CHANGELOG.md
ospd/ospd.py
ospd/scan.py
tests/test_scan_and_result.py

**What**:
Add method to get a single host scan progress
**Why**:
To check the scan progress of a single host.
**How**:
**Checklist**:

Add method to get a single host scan progress

---

CHANGELOG.md
ospd/scan.py
tests/test_scan_and_result.py

**What**:
Fix get_count_total(). Consider 0 value set by the server.
**Why**:
Consider the possibility that the server finds 0 alive hosts, and it must not
be overwritten with the value calculated by ospd from the target.
None means that it was not set, 0 if set by the server and must not be overwritten.
**How**:
Start a scan with a single host name in the target which can't be resolved. Without the patch it ends as interrupted. With the patch the scan finishes as expected.
**Checklist**:

Fix get_count_total(). Consider 0 value set by the server.

---

CHANGELOG.md
ospd/ospd.py
ospd/scan.py
tests/test_scan_and_result.py

**What**:
Remove invalid exclude hosts which do not belongs to the target
**Why**:
Excluded hosts which don't belong to the target generate interrupted scans, because a wrong scan progress calculation
**How**:
- Create a target: 192.168.0.0/24
- Exclude hosts: 192.168.0.1-192.168.0.200, 10.0.0.0/24 <--- this network is not in the target above.
- Run the scan.
With the patch, the scan should  end as expected. Without the patch, it ends as interrupted.
￼
**Checklist**:

Remove exclude hosts which do not belong to the target

---

CHANGELOG.md
ospd/scan.py
tests/test_scan_and_result.py

**What**:
Improve log message.
**Why**:
Actually, no host is removed from the excluded_hosts list. Just the
amount host is ajusted for the scan progress calculation
The excluded_hosts list can have also vhost, which couldn't be part
of the target.
**How**:
**Checklist**:

Improve log message.

---

CHANGELOG.md
ospd/logger.py

**What**:
The logger now uses UTC for timestamps.
**Why**:
GVM, GSA and openVAS-Scanner used UTC and ospd-openvas used local time.
**How**:
When initializing the Logger the timezone is set to UTC. It works when starting ospd-openvas.
**Checklist**:

Changed timezone of logger to UTC

---

CHANGELOG.md
ospd/ospd.py
tests/test_scan_and_result.py

**What**:
￼Wait a minute between scans starts.
**Why**:
Currently the queue system in ospd prevents to start a new scan if there is not enough available memory. This produces that new scans are put in the queue, while the memory condition is not satisfied.
Once some memory is released, all scans in queue are started. In the issue mentioned above, I pasted what I found in the log.
**How**:
- Set min_free_mem_scan_queue option to some value, to avoid starting scans.
- Start many task
- release memory to allow queued scans to start.
- Check in the log that the time between takes about a minute, and the queued scans are not started all together. 
**Checklist**:

Queue wait time

---

CHANGELOG.md
ospd/misc.py

**What**:
Remove the pid file if there is no process for the pid or the process name does not match.
**Why**:
To avoid removing the pidfile manually when ospd scanner was killed or stopped abruptly.
**How**:
- Start ospd-openvas. Try start it again. It should not be possible.
- Killall -9 ospd-openvas
- check that the pid file still exists but there is no process
- start ospd-openvas. The daemon should be started and the pid file should contain the pid of the running ospd-openvas.
**Checklist**:

Remove the pid file if there is no process for the pid or the process name does not match.

---

CHANGELOG.md
ospd/command/command.py

**What**:
Fix regex of gvmcg titles for get_performance command
**Why**:
To get expected behavior.
**How**:
```
gvm-cli --protocol OSP socket --socketpath=/run/ospd/openvas.sock --xml "<get_performance start='0' titles='interface-eth0-err'/>"
```
You will get `status_text="Arguments not allowed"` before applied PR. After you will probably get `No such file or directory: 'gvmcg': 'gvmcg'` but thats fine and expected if you do not have it installed.
**Checklist**:

Fix regex of gvmcg titles for get_performance command

---

CHANGELOG.md
ospd/parser.py

**What**:
Added Setting to enable MQTT for ospd-openvas. This settings allows to set the MQTT broker. Leave it empty to use redis instead.
**Why**:
To support MQTT.
**How**:
Test it via ospd-openvas.
**Checklist**:

Added option to enable mqtt

---

CHANGELOG.md
ospd/parser.py

**What**:
* /var/run is just a symlink to /run nowadays.
* Allow user and group to access to socket by default. This allows for
querying data from osp in a multi-user setup more easily.
* Move pid file within /run/ospd
* There is no /usr/var directory by default. Therefore change the path
to the certs to something that makes sense
**Why**:
**How**:
**Checklist**:

Use better defaults for file paths and permissions

---

CHANGELOG.md
ospd/ospd.py

**What**:
In order to change the stop scan feature some changes are made in ospd as well.
Dependent on: https://github.com/greenbone/ospd-openvas/pull/450
**Why**:
Imrpoving the ospd-openvas structure.
**How**:
**Checklist**:

Improve structure

---

CHANGELOG.md
pyproject.toml

**What**:
Downgrade required version for psutil to 5.5.1
**Why**:
Because the referecen system Debian Buster offers this version.
**How**:
**Checklist**:

Downgrade required version for psutil to 5.5.1
